# yaml-language-server: $schema=https://www.alexmond.org/spring-boot-config-json-schema/sample/boot-generic-config.json

logging:
  level:
    root: DEBUG
    com.spring: DEBUG
    com.java: DEBUG
    com:
      test: DEBUG
      test2: DEBUG
      testing:
        test3: INFO

spring:
  datasource:
    name: test





